### ISSUE TITLE
'log_dir' is defined twice problem 

### ISSUE THREAD

**Issue by s-sanyal** [yuke93/RL-Restore#16]
@yuke93  I recently faced an issue while using this project on Google Colab which says the following : 

`Traceback (most recent call last):
  File "/content/RL-Restore/main.py", line 18, in <module>
    flags.DEFINE_string('log_dir', 'logs/', 'Path for logs')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_defines.py", line 82, in DEFINE
    flag_values, module_name)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_defines.py", line 104, in DEFINE_flag
    fv[flag.name] = flag
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 430, in __setitem__
    raise _exceptions.DuplicateFlagError.from_flag(name, self)
absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from /content/RL-Restore/main.py.  Description from first occurrence: directory to write logfiles into
`

Could you please help me to get rid of this issue. Thanks in advance :)

**Comment by yuke93** [comment]
Hi @s-sanyal ,

You may refer to https://github.com/tensorflow/tensorflow/issues/30472.
