### ISSUE TITLE
Excecution failure

### ISSUE THREAD

**Issue by hernan3009** [yuke93/RL-Restore#2]
Hello, 

I came here after looking the awesome results reported in your paper, I do not do research in your field but I wish to try your code on some low quality images I own, just for fun.

I tried to run your code in Python3 (using conda) without success. Because of some errors (that I fixed) related to lack of parenthesis in the print function I thought I was due to the code is in Python 2 language.

I set up a Python 2.7 environment but I get the same error:

> hernan@hernan-Aspire-ES1-572:~/_apps/LR_RESTORE/RL-Restore-master$
 python main.py --dataset moderate
2018-07-18 19:13:18.588236: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    tf.app.run()
  File "/home/hernan/miniconda3/envs/Python27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 24, in main
    config = get_config(FLAGS)
  File "/home/hernan/_apps/LR_RESTORE/RL-Restore-master/config.py", line 64, in get_config
    for k, v in FLAGS.__dict__['__flags'].items():
KeyError: '__flags'

Is this a code issue or I am doing something wrong?

Thank you

**Comment by yuke93** [comment]
Hi @hernan3009,

The current code is indeed implemented on Python 2.7. Your reported error may be caused by Tensorflow version. Please refer to this [link](https://stackoverflow.com/questions/48837940/tensorflow-tf-flag-issue-flags-dict-flags-items) if your TF version is higher than 1.4.

**Comment by hernan3009** [comment]
Just to confirm that the problem was due to the TF version and was solved following the link above.

Regards
